version: '3'

services:
  docmost:
    image: docker.io/library/docmost:latest
    depends_on:
      - db
      - redis
    environment:
      APP_URL: 'http://localhost:3000'
      APP_SECRET: 'REPLACE_WITH_LONG_SECRET'
      DATABASE_URL: 'postgresql://postgres:password@db:5432/docmost?schema=public'
      REDIS_URL: 'redis://redis:6379'
      STORAGE_DRIVER: 'local'
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - local_storage:/app/data/storage

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: docmost
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7.2-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  local_storage:
  db_data:
  redis_data:
